name: Miller Companies
favicon: null
layout_spectrum: 0.03249407769180834
typography_spectrum: 0.8447598877828568
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9790925313718617
  lightness: 0.04840214643627405
  saturation: 0.9372166153043509
  rhythmicContrast: 0.9111098849680275
purpose: []
